'setting.accountLinking': 'Initiate Account Linking',
'setting.accountNumberContain': 'Account number can only contain numbers',
'setting.accountNumberLength': 'Account number must be between 4 and 17 characters',
'setting.accountNumberRequired': 'Account number is required.',
'setting.accountType': 'Account Type',
'setting.accountTypeRequired': 'Account type is required.',
'setting.ach': 'ach',
'setting.actionRequired': 'Action Required',
'setting.addCodeOfConduct': 'Add Code of Conduct',
'setting.addCustomField': 'Add Custom Field Set to All Assignments',
'setting.addEmployeesIcon': 'Add Employees Icon',
'setting.addFundsIcon': 'Add Funds Icon',
'setting.addIndividually': 'Add Individually',
'setting.addTermsAgreement': 'Add Terms of Agreement',
'setting.addToFileManager': 'Add file to File Manager',
'setting.addressRequired': 'Address is required.',
'setting.agreeToCommunicationTerms': 'I read and agree to WorkMarket Electronic Communcations Delivery Policy stated in the Terms of Use. I understand that Work Market will provide me with information about my account electronically. I confirm that I can access emails, web pages, and PDF files.',
'setting.assignedWorker': 'Assigned Worker',
'setting.assignmentPreferencesIcon': 'Assignment Preferences Icon',
'setting.assignmentPrintoutIcon': 'Assignment Printout Icon',
'setting.atLeastOnePayment': 'At least one payment term length must be available',
'setting.atLeastOnePaymentMethod': 'You must first select at least one payment method.',
'setting.bankNameRequired': 'Bank name is required.',
'setting.beneficialOwner': 'Type of beneficial owner',
'setting.businessDisregardedEntity': 'Business name / Disregarded entity name',
'setting.businessNumber': 'Business Number',
'setting.changingPaymentConfiguration': 'You are changing your payment configuration and you currently have unpaid invoices. All existing invoices will remain on the current invoicing scheme with originally selected payment terms. Assignments created after saving your change will use your new payment settings. Are you sure you want to continue?',
'setting.checking': 'checking',
'setting.cityRequired': 'City is required.',
'setting.company': 'company',
'setting.companyNameRequired': 'Company name is required.',
'setting.completeCopy': 'Complete Copy',
'setting.conductIcon': 'Code of Conduct Icon',
'setting.configurePaymentTerm': 'Configure payment terms, Code of Conduct, and more.',
'setting.confirmAccountNumber': 'Confirm Account Number',
'setting.copyCustomField': 'Copy Custom Field Set',
'setting.couldNotDisableWebhook': 'Could not disable webhook, please try again.',
'setting.couldNotEnableWebhook': 'Could not enable webhook, please try again.',
'setting.countryOfIncorporation': 'Country of incorporation',
'setting.customFieldsIcon': 'Custom Fields Icon',
'setting.customFieldsImg': 'CustomFields Img',
'setting.deleteHeader': 'Are you sure you want to delete this header?',
'setting.deleteWebhook': 'Are you sure you want to delete this webhook?',
'setting.deletingPermanentlyHistoricData': 'Warning: deleting will permanently remove all historic data associated with this custom label. This cannot be undone. Are you absolutely sure?',
'setting.deliverablesIcon': 'Deliverables Icon',
'setting.deliverablesImg': 'Deliverables Img',
'setting.depositAppearVerifyAmount': 'Once these deposits appear in your account (approximately 3 days), you\'ll need to verify the deposit amount in Settings > Payment Accounts.',
'setting.disableBudgetFeature': 'Are you sure you want to disable your project budget feature? Disabling this feature will remove all current budget values from all your projects.',
'setting.disregardedEntity': 'Disregarded entity',
'setting.disregardedEntityName': 'Do you have a business name or disregarded entity name that is different than the name that you provided above, such as a doing business as (DBA) name?',
'setting.documentsImg': 'Documents Img',
'setting.empAddedSuccessfully': 'Employee added successfully.',
'setting.employeeId': 'Employer ID Number',
'setting.enterPhoneNumber': 'Enter Your Phone Number',
'setting.enterTemplate': 'Enter template name',
'setting.errorAddingFile': 'There was an error adding this file to the filemanager.',
'setting.errorProcessingFileUpload': 'There was an error in processing the file. Please upload the file again.',
'setting.errorRetrievingEntitlements': 'There was an error retrieving entitlements in the creation modal.',
'setting.errorUploadingFile': 'There was an error in uploading the file. Please upload the file again.',
'setting.errorWithFileAndMapping': 'The following errors were found with the source file and mapping:',
'setting.failedActiveTemplate': 'Failed to activate template.',
'setting.failedDeactivateTemplate': 'Failed to deactivate template .',
'setting.failedDeleteTemplate': 'Failed to delete template.',
'setting.federalTax': 'Federal Tax Classification',
'setting.fileCurrentlyUploaded': 'Your file is currently being uploaded. You should get the status of your upload via notifications.',
'setting.fillOutBelow': 'Fill out the form below to initiate two small deposits into your bank account.',
'setting.firstAssignmentIcon': 'First Assignment Icon',
'setting.ifDifferent': 'Only enter if different from above',
'setting.includeDetails': 'Include details on business conduct, professionalism, attire, and behavior. This information displays on the assignment detail and printout. Limit of 200 characters.',
'setting.internalOwner': 'Internal Owner',
'setting.invalidUrl': 'The URL provided is not valid.',
'setting.liabilityCompany': 'Limited Liability Company',
'setting.linkBankAccountForEasyFunding': 'Link your bank account for easy funding in the future.',
'setting.linkBankAccountIcon': 'Link Bank Account Icon',
'setting.mailCheck': 'Mail a Check',
'setting.metaData': 'Work Market Metadata',
'setting.myLogo': 'My Logo',
'setting.nameOn': 'Name On Account',
'setting.nameOnAccount': 'Name on Account number is required.',
'setting.needBitMoreInformation': 'Welcome to Work Market. To help you make the most of the platform, we need a bit more information from you.',
'setting.newCopiedCustomField': '<p>Please name for your new copied Custom Field Set below.</p><input type="text" id="copy_name" name="copy_name" maxlength="256" class="span5" value="" placeholder="Enter here..." />',
'setting.noActiveTemplates': '<p>You currently have no active templates.</p>',
'setting.noBlockCompanies': '<div class="alert">You currently have no blocked companies.</div>',
	'setting.notRemoveTryAgain': 'Could not remove webhook, please try again.',
	'setting.notSaveWebhook': 'Could not save webhook, please try again.',
'setting.numberLimit': 'number of characters. The limit is 200 characters.',
'setting.paymentPreview': 'Payment Terms Preview',
'setting.paymentTermsImg': 'Payment Terms Img',
'setting.postalRequired': 'Zip/Postal code is required.',
'setting.problemSubmittingRequest': 'There was a problem submitting your request',
'setting.province': 'Province',
'setting.readyToSetFirstAssignment': 'Your assignment preferences are complete and you\'re  now ready to set up your first assignment.',
'setting.removeDevice': 'Are you sure you want to remove this device?',
'setting.removeSms': 'Are you certain you want to remove this SMS phone?',
'setting.requireCustomField': 'Require Custom Field Set',
'setting.requireFieldset': '<p>Are you sure you want to require this fieldset?</p><p>Warning: All existing templates will update to use this fieldset and overwrite previous template settings, removing all currently added custom field sets. This will not affect existing assignments.</p>',
'setting.requirementImg': 'Requirements Img',
'setting.requirementsIcon': 'Requirements Icon',
'setting.residenceAddress': 'Permanent residence address',
'setting.resourceBadge': 'Resource Badge Preview',
'setting.routingNumber': 'Routing Number',
'setting.routingNumberLength': 'Routing number must be 9 characters.',
'setting.routingNumberRequired': 'Rounting number is required.',
'setting.sampleAssignment': 'Sample Assignment',
'setting.sampleAssignmentPrintout': 'Sample Assignment Printout',
'setting.saveWithoutPayment': 'Are you sure you want to save without setting your payment terms?',
'setting.securityCode': 'Security code',
'setting.selectDayToIssuePayment': 'You must first select a day to issue payments.',
'setting.selectPaymentType': 'You must first select a payment type.',
'setting.shipmentsIcon': 'Shipments Icon',
'setting.shipmentsImg': 'Shipments Img',
'setting.smsConfirmed': 'SMS successfully confirmed!',
'setting.stateProvince': 'State or Province',
'setting.taxNumberRequired': 'Tax number is required.',
'setting.templatesIcon': 'Templates Icon',
'setting.uniqueLabel': 'Unique ID Label',
'setting.updateAgreementRemovePoolMember': '<p>Updating an agreement will remove all current members of any talent pool using this agreement as a requirement. This will give members of affected talent pools an opportunity to re-sign your updated agreement. This may take a few minutes to complete, depending on the size of your talent pool.</p><p>Do you want to continue?</p>',
'setting.uploadFailed': 'Upload failed',
'setting.verifyNumber': 'Verify Your Phone Number',
'setting.wMLogo': 'Work Market Logo',
'setting.wireTransfer': 'Wire Transfer',
